### ISSUE TITLE
info file defines an unknown settings location

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/views_aggregator#4]
In the .info it says:

> configure = admin/config/content/views_aggregator

but that location isn't defined in this module.

**Comment by argiepiano** [comment]
Thanks for reporting! I will remove this location for now. The latest version in PR #7 adds a config file. Eventually we'll need to add a configuration page to configure a few settings for views_aggregator. I will leave this issue open until such a page is added.

**Comment by argiepiano** [comment]
This was fixed 3 years ago.
